import { FolderDetail } from "@/types/folder";

export const defaultFolderData: FolderDetail[] = [
  {
    id: "tech",
    name: "Công nghệ",
    desc: "Các từ vựng về AI, Web và Dữ liệu",
    words: [
      {
        id: 101,
        word: "Algorithm",
        meaning: "Thuật toán",
        phonetic: "/ˈæl.ɡə.rɪ.ðəm/",
        pos: "Noun",
        example: "Machine learning relies on complex algorithms to process data.",
        image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200",
        learned: true,
      },
      {
        id: 102,
        word: "Database",
        meaning: "Cơ sở dữ liệu",
        phonetic: "/ˈdeɪ.tə.beɪs/",
        pos: "Noun",
        example: "The customer information is stored securely in the centralized database.",
        image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=200",
        learned: false,
      },
      {
        id: 103,
        word: "Deploy",
        meaning: "Triển khai",
        phonetic: "/dɪˈplɔɪ/",
        pos: "Verb",
        example: "We will deploy the new application build to the production server tonight.",
        image: "https://images.unsplash.com/photo-1600132806370-bf17e65e942f?w=200",
        learned: false,
      },
      {
        id: 104,
        word: "Scalable",
        meaning: "Có thể mở rộng",
        phonetic: "/ˈskeɪ.lə.bəl/",
        pos: "Adjective",
        example: "We need a scalable architecture that can handle millions of users.",
        image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=200",
        learned: true,
      },
      {
        id: 105,
        word: "Framework",
        meaning: "Khung làm việc",
        phonetic: "/ˈfreɪm.wɜːk/",
        pos: "Noun",
        example: "Next.js is a popular React framework for building web applications.",
        image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=200",
        learned: false,
      },
      {
        id: 106,
        word: "Interface",
        meaning: "Giao diện",
        phonetic: "/ˈɪn.tə.feɪs/",
        pos: "Noun",
        example: "The new user interface is much more intuitive.",
        image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=200",
        learned: true,
      },
      {
        id: 107,
        word: "Authenticate",
        meaning: "Xác thực",
        phonetic: "/ɔːˈθen.tɪ.keɪt/",
        pos: "Verb",
        example: "You must authenticate before accessing the private data.",
        image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=200",
        learned: false,
      },
      {
        id: 108,
        word: "Responsive",
        meaning: "Phản hồi nhanh / Tương thích",
        phonetic: "/rɪˈspɒn.sɪv/",
        pos: "Adjective",
        example: "A responsive website adapts to different screen sizes.",
        image: "https://images.unsplash.com/photo-1526498460520-4c246339dccb?w=200",
        learned: false,
      }
    ],
  },
  {
    id: "comm",
    name: "Giao tiếp cơ bản",
    desc: "Tiếng Anh giao tiếp hàng ngày",
    words: [
      {
        id: 201,
        word: "Negotiate",
        meaning: "Đàm phán",
        phonetic: "/nəˈɡəʊ.ʃi.eɪt/",
        pos: "Verb",
        example: "We need to negotiate a better deal with the supplier.",
        learned: false,
      },
      {
        id: 202,
        word: "Persuade",
        meaning: "Thuyết phục",
        phonetic: "/pəˈsweɪd/",
        pos: "Verb",
        example: "He managed to persuade the team to adopt his new strategy.",
        learned: true,
      },
      {
        id: 203,
        word: "Collaborate",
        meaning: "Hợp tác",
        phonetic: "/kəˈlæb.ə.reɪt/",
        pos: "Verb",
        example: "Two teams will collaborate on this new project.",
        learned: false,
      },
      {
        id: 204,
        word: "Clarify",
        meaning: "Làm rõ",
        phonetic: "/ˈklær.ɪ.faɪ/",
        pos: "Verb",
        example: "Could you clarify what you mean by that?",
        learned: false,
      }
    ],
  }
];
